### ISSUE TITLE
What's up Yeoman-Environment

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/environment#2]
To be good semver citizens I guess our first release will be 1.0 (plus the system have been pretty stable as it's only extracted from yeoman-generator).

So, it's a good occasion to drop the bad parts. I open this thread as a free discussion. I'd prefer we keep changes small and focused, but bigger ideas are welcomed too.
#### Todos for 1.0
- [x] Remove property aliases (`args` <> `arguments`, etc) - These are just confusing. Let's stick with one version.
- [x] Remove multiple kind of data expected. We often allow Strings with spaces or Array as parameter - let's just accept array.
- [x] Generate Environment API doc
- [x] Port yeoman-generator to use this module (of course)
- [x] Port yo to use this module
